# Generated by Django 5.0.2 on 2026-02-11 17:15

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=20, unique=True, verbose_name='Πινακίδα')),
                ('vin', models.CharField(blank=True, max_length=17, null=True, unique=True, verbose_name='VIN')),
                ('make', models.CharField(max_length=50, verbose_name='Μάρκα')),
                ('model', models.CharField(max_length=50, verbose_name='Μοντέλο')),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)], verbose_name='Έτος Κατασκευής')),
                ('purchase_date', models.DateField(verbose_name='Ημ/νία Αγοράς')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Τιμή Αγοράς (€)')),
                ('insurance_expiry', models.DateField(verbose_name='Λήξη Ασφάλισης')),
                ('kteo_expiry', models.DateField(verbose_name='Λήξη ΚΤΕΟ')),
                ('circulation_tax_paid', models.BooleanField(default=False, verbose_name='Τέλη Κυκλοφορίας Πληρωμένα')),
                ('status', models.CharField(choices=[('ACTIVE', 'Ενεργό'), ('MAINTENANCE', 'Σε Συντήρηση'), ('INACTIVE', 'Ανενεργό'), ('SOLD', 'Πωλήθηκε')], default='ACTIVE', max_length=20, verbose_name='Κατάσταση')),
                ('current_odometer', models.PositiveIntegerField(default=0, verbose_name='Τρέχον Χιλιόμετρα')),
                ('notes', models.TextField(blank=True, verbose_name='Σημειώσεις')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Όχημα',
                'verbose_name_plural': 'Οχήματα',
                'ordering': ['plate'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Επωνυμία Εταιρείας')),
                ('tax_id', models.CharField(max_length=20, unique=True, verbose_name='ΑΦΜ')),
                ('doy', models.CharField(blank=True, max_length=100, verbose_name='ΔΟΥ')),
                ('address', models.TextField(blank=True, verbose_name='Διεύθυνση')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Τηλέφωνο')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('business_type', models.CharField(choices=[('TRANSPORT', 'Μεταφορές Εμπορευμάτων'), ('PASSENGER', 'Μεταφορές Επιβατών'), ('TAXI', 'Ταξί'), ('TOUR', 'Τουριστικά'), ('CORPORATE', 'Εταιρικός Στόλος'), ('MIXED', 'Μικτός Στόλος')], default='MIXED', max_length=20, verbose_name='Τύπος Επιχείρησης')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ενεργή')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Εταιρεία',
                'verbose_name_plural': 'Εταιρείες',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('vehicleasset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.vehicleasset')),
                ('bus_type', models.CharField(choices=[('URBAN', 'Αστικό'), ('INTERCITY', 'Υπεραστικό'), ('TOUR', 'Τουριστικό'), ('SCHOOL', 'Σχολικό'), ('MINIVAN', 'Minivan')], default='TOUR', max_length=20, verbose_name='Τύπος Λεωφορείου')),
                ('seat_count', models.PositiveIntegerField(verbose_name='Αριθμός Θέσεων')),
                ('standing_capacity', models.PositiveIntegerField(default=0, verbose_name='Όρθιοι Επιβάτες')),
                ('has_wifi', models.BooleanField(default=False, verbose_name='WiFi')),
                ('has_toilet', models.BooleanField(default=False, verbose_name='WC')),
                ('has_ac', models.BooleanField(default=True, verbose_name='Κλιματισμός')),
                ('passenger_insurance_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ασφάλιση Επιβατών (€)')),
            ],
            options={
                'verbose_name': 'Λεωφορείο',
                'verbose_name_plural': 'Λεωφορεία',
            },
            bases=('core.vehicleasset',),
        ),
        migrations.CreateModel(
            name='Moto',
            fields=[
                ('vehicleasset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.vehicleasset')),
                ('moto_type', models.CharField(choices=[('SCOOTER', 'Scooter'), ('MOTORCYCLE', 'Μοτοσυκλέτα'), ('DELIVERY', 'Delivery Bike')], default='SCOOTER', max_length=20, verbose_name='Τύπος Μοτοσυκλέτας')),
                ('engine_cc', models.PositiveIntegerField(verbose_name='Κυβικά (cc)')),
                ('has_top_case', models.BooleanField(default=False, verbose_name='Έχει Top Case')),
                ('max_cargo_kg', models.PositiveIntegerField(default=0, verbose_name='Μέγιστο Φορτίο (kg)')),
            ],
            options={
                'verbose_name': 'Μοτοσυκλέτα',
                'verbose_name_plural': 'Μοτοσυκλέτες',
            },
            bases=('core.vehicleasset',),
        ),
        migrations.CreateModel(
            name='PassengerCar',
            fields=[
                ('vehicleasset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.vehicleasset')),
                ('car_type', models.CharField(choices=[('SEDAN', 'Sedan'), ('HATCHBACK', 'Hatchback'), ('SUV', 'SUV'), ('STATION_WAGON', 'Station Wagon'), ('TAXI', 'Ταξί')], default='SEDAN', max_length=20, verbose_name='Τύπος Αυτοκινήτου')),
                ('is_taxi', models.BooleanField(default=False, verbose_name='Είναι Ταξί')),
                ('taximeter_serial', models.CharField(blank=True, max_length=50, verbose_name='Σειριακός Ταξιμέτρου')),
                ('taxi_license_number', models.CharField(blank=True, max_length=20, verbose_name='Αριθμός Άδειας Ταξί')),
                ('shift_type', models.CharField(blank=True, choices=[('SINGLE', 'Μονή Βάρδια'), ('DOUBLE', 'Διπλή Βάρδια (Συνταιρία)')], max_length=10, verbose_name='Τύπος Βάρδιας')),
                ('is_leased', models.BooleanField(default=False, verbose_name='Είναι Leasing')),
                ('leasing_company', models.CharField(blank=True, max_length=100, verbose_name='Εταιρεία Leasing')),
                ('leasing_monthly_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Μηνιαίο Κόστος Leasing (€)')),
                ('bik_tax_value', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Φορολογητέα Αξία BiK (€)')),
            ],
            options={
                'verbose_name': 'Επιβατικό Αυτοκίνητο',
                'verbose_name_plural': 'Επιβατικά Αυτοκίνητα',
            },
            bases=('core.vehicleasset',),
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('vehicleasset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.vehicleasset')),
                ('truck_type', models.CharField(choices=[('RIGID', 'Φορτηγό Άκαμπτο'), ('ARTICULATED', 'Νταλίκα'), ('TANKER', 'Βυτιοφόρο'), ('REFRIGERATED', 'Ψυγείο')], default='RIGID', max_length=20, verbose_name='Τύπος Φορτηγού')),
                ('tachograph_serial', models.CharField(blank=True, max_length=50, verbose_name='Σειριακός Ταχογράφου')),
                ('tachograph_calibration_date', models.DateField(blank=True, null=True, verbose_name='Ημ/νία Βαθμονόμησης Ταχογράφου')),
                ('has_adr', models.BooleanField(default=False, verbose_name='Έχει ADR')),
                ('adr_expiry', models.DateField(blank=True, null=True, verbose_name='Λήξη ADR')),
                ('axle_count', models.PositiveIntegerField(default=2, verbose_name='Αριθμός Αξόνων')),
                ('max_load_kg', models.PositiveIntegerField(verbose_name='Μέγιστο Φορτίο (kg)')),
                ('trailer_plate', models.CharField(blank=True, max_length=20, verbose_name='Πινακίδα Ρυμουλκούμενου')),
            ],
            options={
                'verbose_name': 'Φορτηγό',
                'verbose_name_plural': 'Φορτηγά',
            },
            bases=('core.vehicleasset',),
        ),
        migrations.AddField(
            model_name='vehicleasset',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='core.company', verbose_name='Εταιρεία'),
        ),
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='Τηλέφωνο')),
                ('address', models.TextField(blank=True, verbose_name='Διεύθυνση')),
                ('date_of_birth', models.DateField(verbose_name='Ημ/νία Γέννησης')),
                ('license_categories', models.CharField(max_length=50, verbose_name='Κατηγορίες Άδειας (π.χ. B,C,E)')),
                ('license_number', models.CharField(max_length=20, unique=True, verbose_name='Αριθμός Άδειας')),
                ('license_issue_date', models.DateField(verbose_name='Ημ/νία Έκδοσης Άδειας')),
                ('license_expiry_date', models.DateField(verbose_name='Λήξη Άδειας')),
                ('has_cpc', models.BooleanField(default=False, verbose_name='Έχει ΠΕΙ')),
                ('cpc_number', models.CharField(blank=True, max_length=50, verbose_name='Αριθμός ΠΕΙ')),
                ('cpc_expiry_date', models.DateField(blank=True, null=True, verbose_name='Λήξη ΠΕΙ')),
                ('medical_exam_date', models.DateField(verbose_name='Ημ/νία Ιατρικής Εξέτασης')),
                ('medical_exam_expiry', models.DateField(verbose_name='Λήξη Ιατρικής')),
                ('license_points', models.PositiveIntegerField(default=12, validators=[django.core.validators.MaxValueValidator(12)], verbose_name='Βαθμοί Άδειας (Σύστημα Σησάμι)')),
                ('hire_date', models.DateField(verbose_name='Ημ/νία Πρόσληψης')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ενεργός')),
                ('notes', models.TextField(blank=True, verbose_name='Σημειώσεις')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='core.company', verbose_name='Εταιρεία')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL, verbose_name='Χρήστης')),
            ],
            options={
                'verbose_name': 'Προφίλ Οδηγού',
                'verbose_name_plural': 'Προφίλ Οδηγών',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
    ]
