# Generated by Django 5.0.2 on 2026-02-11 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taxi',
            fields=[
                ('vehicleasset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.vehicleasset')),
                ('taximeter_serial', models.CharField(max_length=50, verbose_name='Σειριακός Ταξιμέτρου')),
                ('license_type_edras', models.CharField(choices=[('EDRAS', 'Έδρας'), ('AGORAS', 'Αγοράς')], default='EDRAS', max_length=10, verbose_name='Τύπος Άδειας')),
            ],
            options={
                'verbose_name': 'Ταξί',
                'verbose_name_plural': 'Ταξί',
            },
            bases=('core.vehicleasset',),
        ),
        migrations.RemoveField(
            model_name='bus',
            name='has_ac',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='has_wifi',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='passenger_insurance_amount',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='standing_capacity',
        ),
        migrations.RemoveField(
            model_name='driverprofile',
            name='cpc_expiry_date',
        ),
        migrations.RemoveField(
            model_name='driverprofile',
            name='cpc_number',
        ),
        migrations.RemoveField(
            model_name='driverprofile',
            name='has_cpc',
        ),
        migrations.RemoveField(
            model_name='driverprofile',
            name='medical_exam_date',
        ),
        migrations.RemoveField(
            model_name='driverprofile',
            name='medical_exam_expiry',
        ),
        migrations.RemoveField(
            model_name='moto',
            name='has_top_case',
        ),
        migrations.RemoveField(
            model_name='moto',
            name='max_cargo_kg',
        ),
        migrations.RemoveField(
            model_name='passengercar',
            name='bik_tax_value',
        ),
        migrations.RemoveField(
            model_name='passengercar',
            name='is_leased',
        ),
        migrations.RemoveField(
            model_name='passengercar',
            name='is_taxi',
        ),
        migrations.RemoveField(
            model_name='passengercar',
            name='leasing_company',
        ),
        migrations.RemoveField(
            model_name='passengercar',
            name='leasing_monthly_cost',
        ),
        migrations.RemoveField(
            model_name='passengercar',
            name='shift_type',
        ),
        migrations.RemoveField(
            model_name='passengercar',
            name='taxi_license_number',
        ),
        migrations.RemoveField(
            model_name='passengercar',
            name='taximeter_serial',
        ),
        migrations.RemoveField(
            model_name='truck',
            name='adr_expiry',
        ),
        migrations.RemoveField(
            model_name='truck',
            name='axle_count',
        ),
        migrations.RemoveField(
            model_name='truck',
            name='has_adr',
        ),
        migrations.RemoveField(
            model_name='truck',
            name='max_load_kg',
        ),
        migrations.RemoveField(
            model_name='truck',
            name='tachograph_serial',
        ),
        migrations.RemoveField(
            model_name='truck',
            name='trailer_plate',
        ),
        migrations.RemoveField(
            model_name='vehicleasset',
            name='circulation_tax_paid',
        ),
        migrations.AddField(
            model_name='bus',
            name='is_tourist_bus',
            field=models.BooleanField(default=False, verbose_name='Τουριστικό Λεωφορείο'),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='cpc_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='Λήξη ΠΕΙ'),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='medical_card_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='Λήξη Ιατρικής Κάρτας'),
        ),
        migrations.AddField(
            model_name='moto',
            name='box_capacity_liters',
            field=models.PositiveIntegerField(default=0, verbose_name='Χωρητικότητα Box (λίτρα)'),
        ),
        migrations.AddField(
            model_name='passengercar',
            name='bik_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Φορολογητέα Αξία BiK (€)'),
        ),
        migrations.AddField(
            model_name='passengercar',
            name='leasing_contract_end',
            field=models.DateField(blank=True, null=True, verbose_name='Λήξη Σύμβασης Leasing'),
        ),
        migrations.AddField(
            model_name='truck',
            name='axles_count',
            field=models.PositiveIntegerField(default=2, verbose_name='Αριθμός Αξόνων'),
        ),
        migrations.AddField(
            model_name='truck',
            name='is_adr',
            field=models.BooleanField(default=False, verbose_name='Έχει ADR'),
        ),
        migrations.AddField(
            model_name='vehicleasset',
            name='circulation_tax_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='Λήξη Τελών Κυκλοφορίας'),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='license_categories',
            field=models.CharField(help_text='Διαχωρισμένες με κόμμα (π.χ. B,C,E)', max_length=50, verbose_name='Κατηγορίες Άδειας (π.χ. B,C,E)'),
        ),
        migrations.AlterField(
            model_name='passengercar',
            name='car_type',
            field=models.CharField(choices=[('SEDAN', 'Sedan'), ('HATCHBACK', 'Hatchback'), ('SUV', 'SUV'), ('STATION_WAGON', 'Station Wagon')], default='SEDAN', max_length=20, verbose_name='Τύπος Αυτοκινήτου'),
        ),
    ]
