# Generated by Django 5.0.14 on 2026-02-13 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_taxi_remove_bus_has_ac_remove_bus_has_wifi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Τίτλος Θέσης')),
                ('is_driver_role', models.BooleanField(default=False, verbose_name='Θέση Οδηγού')),
            ],
            options={
                'verbose_name': 'Θέση Εργασίας',
                'verbose_name_plural': 'Θέσεις Εργασίας',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Όνομα')),
                ('last_name', models.CharField(max_length=100, verbose_name='Επώνυμο')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ενεργός')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_employees', to='core.vehicleasset', verbose_name='Συνδεδεμένο Όχημα')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='core.company', verbose_name='Εταιρεία')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='core.employeeposition', verbose_name='Θέση')),
            ],
            options={
                'verbose_name': 'Υπάλληλος',
                'verbose_name_plural': 'Υπάλληλοι',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
