# Generated by Django 5.0.14 on 2026-02-13 18:49

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_employeeposition_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='transport_type',
            field=models.CharField(choices=[('FREIGHT', 'Εμπορευματικές Μεταφορές'), ('PASSENGER', 'Επιβατικές Μεταφορές')], default='FREIGHT', max_length=20, verbose_name='Τύπος Μεταφορών'),
        ),
        migrations.AddField(
            model_name='employee',
            name='available_hours_per_year',
            field=models.IntegerField(default=1936, help_text='1936 ώρες = 11 μήνες × 22 ημέρες × 8 ώρες', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Διαθέσιμες Ώρες/Έτος'),
        ),
        migrations.AddField(
            model_name='employee',
            name='employer_contributions_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.22'), help_text='Π.χ. 0.22 για 22%', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('1.00'))], verbose_name='Ποσοστό Εργοδοτικών Εισφορών'),
        ),
        migrations.AddField(
            model_name='employee',
            name='monthly_gross_salary',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Μικτός Μηνιαίος Μισθός (€)'),
        ),
    ]
