# Generated by Django 5.0.14 on 2026-02-14 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_company_transport_type_and_more'),
        ('operations', '0002_vehicle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moto',
            name='vehicleasset_ptr',
        ),
        migrations.RemoveField(
            model_name='passengercar',
            name='vehicleasset_ptr',
        ),
        migrations.RemoveField(
            model_name='taxi',
            name='vehicleasset_ptr',
        ),
        migrations.RemoveField(
            model_name='truck',
            name='vehicleasset_ptr',
        ),
        migrations.RemoveField(
            model_name='vehicleasset',
            name='company',
        ),
        migrations.RemoveField(
            model_name='vehicleasset',
            name='polymorphic_ctype',
        ),
        migrations.AlterField(
            model_name='employee',
            name='assigned_vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_employees', to='operations.vehicle', verbose_name='Συνδεδεμένο Όχημα'),
        ),
        migrations.DeleteModel(
            name='Bus',
        ),
        migrations.DeleteModel(
            name='Moto',
        ),
        migrations.DeleteModel(
            name='PassengerCar',
        ),
        migrations.DeleteModel(
            name='Taxi',
        ),
        migrations.DeleteModel(
            name='Truck',
        ),
    ]
