# Generated by Django 5.0.14 on 2026-02-14 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_moto_vehicleasset_ptr_and_more'),
        ('finance', '0010_alter_transportorder_assigned_vehicle'),
        ('operations', '0003_alter_vehicle_options_vehicle_adr_expiry_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VehicleAsset',
        ),
    ]
