# Generated by Django 5.0.2 on 2026-02-15 18:36

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_delete_vehicleasset'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='utilization_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.85'), help_text='Π.χ. 0.85 για 85% - Μέσος όρος χρήσης οχημάτων', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('1.00'))], verbose_name='Ποσοστό Αξιοποίησης Στόλου'),
        ),
        migrations.AddField(
            model_name='company',
            name='working_days_per_year',
            field=models.IntegerField(default=252, help_text='Τυπικά 252 ημέρες (365 - 52 Σαββατοκύριακα - αργίες)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)], verbose_name='Εργάσιμες Ημέρες/Έτος'),
        ),
        migrations.AddField(
            model_name='company',
            name='working_hours_per_day',
            field=models.IntegerField(default=8, help_text='Τυπικά 8 ώρες', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)], verbose_name='Ώρες Εργασίας/Ημέρα'),
        ),
    ]
