# Generated by Django 5.0.14 on 2026-02-21 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_company_utilization_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='subscription_expires_at',
            field=models.DateTimeField(blank=True, help_text='Αν κενό, δεν υπάρχει όριο λήξης', null=True, verbose_name='Λήξη Συνδρομής'),
        ),
        migrations.AddField(
            model_name='company',
            name='subscription_status',
            field=models.CharField(choices=[('TRIAL', 'Δοκιμαστική Περίοδος'), ('ACTIVE', 'Ενεργή'), ('EXPIRED', 'Ληγμένη')], default='ACTIVE', max_length=20, verbose_name='Κατάσταση Συνδρομής'),
        ),
        migrations.AddField(
            model_name='company',
            name='vehicle_limit',
            field=models.PositiveIntegerField(blank=True, help_text='Μέγιστος αριθμός οχημάτων (null = απεριόριστο)', null=True, verbose_name='Όριο Οχημάτων'),
        ),
    ]
