# Generated by Django 5.0.14 on 2026-02-26 19:21

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_subscription_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='assigned_vehicle',
        ),
        migrations.AddField(
            model_name='employee',
            name='adr_category',
            field=models.CharField(blank=True, help_text='Π1-Π9 για επικίνδυνα εμπορεύματα', max_length=10, verbose_name='Κατηγορία ADR'),
        ),
        migrations.AddField(
            model_name='employee',
            name='adr_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='Λήξη ADR'),
        ),
        migrations.AddField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Ημ/νία Γέννησης'),
        ),
        migrations.AddField(
            model_name='employee',
            name='driver_license_categories',
            field=models.CharField(blank=True, help_text='π.χ. B,C,CE,D,DE', max_length=50, verbose_name='Κατηγορίες Άδειας'),
        ),
        migrations.AddField(
            model_name='employee',
            name='driver_license_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='Λήξη Άδειας Οδήγησης'),
        ),
        migrations.AddField(
            model_name='employee',
            name='driver_license_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Αριθμός Άδειας Οδήγησης'),
        ),
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Τηλέφωνο'),
        ),
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='employees/photos/', verbose_name='Φωτογραφία'),
        ),
        migrations.AddField(
            model_name='employee',
            name='tachograph_card_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='Λήξη Κάρτας Ταχογράφου'),
        ),
        migrations.AddField(
            model_name='employee',
            name='tachograph_card_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Αριθμός Ψηφιακού Ταχογράφου'),
        ),
        migrations.CreateModel(
            name='EmployeeLeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Έτος')),
                ('annual_entitled', models.DecimalField(decimal_places=1, default=Decimal('20.0'), max_digits=5, verbose_name='Δικαίωμα Ετήσιας Άδειας (ημέρες)')),
                ('annual_taken', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=5, verbose_name='Ληφθείσα Ετήσια Άδεια (ημέρες)')),
                ('sick_taken', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=5, verbose_name='Ληφθείσα Αναρρωτική (ημέρες)')),
                ('other_taken', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=5, verbose_name='Άλλες Άδειες (ημέρες)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='core.employee', verbose_name='Υπάλληλος')),
            ],
            options={
                'verbose_name': 'Υπόλοιπο Αδειών Υπαλλήλου',
                'verbose_name_plural': 'Υπόλοιπα Αδειών Υπαλλήλων',
                'ordering': ['-year', 'employee__last_name'],
                'unique_together': {('employee', 'year')},
            },
        ),
    ]
