# Generated by Django 5.0.14 on 2026-02-27 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_employee_vehicle_add_personnel_driver_fields'),
        ('finance', '0014_costcenter_driver_to_employee'),
        ('operations', '0007_driverprofile_to_employee_driver'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DriverProfile',
        ),
    ]
