# Generated by Django 5.0.14 on 2026-02-28 22:54

import django.db.models.deletion
from django.db import migrations, models


def seed_license_categories(apps, schema_editor):
    """Seed driving license categories"""
    DrivingLicenseCategory = apps.get_model('core', 'DrivingLicenseCategory')
    
    categories = [
        {'code': 'AM', 'label_el': 'Μοτοποδήλατο', 'label_en': 'Moped', 'display_order': 1},
        {'code': 'A1', 'label_el': 'Μοτοσικλέτα έως 125cc', 'label_en': 'Motorcycle up to 125cc', 'display_order': 2},
        {'code': 'A2', 'label_el': 'Μοτοσικλέτα έως 35kW', 'label_en': 'Motorcycle up to 35kW', 'display_order': 3},
        {'code': 'A', 'label_el': 'Μοτοσικλέτα', 'label_en': 'Motorcycle', 'display_order': 4},
        {'code': 'B', 'label_el': 'Επιβατικό αυτοκίνητο', 'label_en': 'Passenger Car', 'display_order': 5},
        {'code': 'BE', 'label_el': 'Επιβατικό με ρυμουλκούμενο', 'label_en': 'Car with Trailer', 'display_order': 6},
        {'code': 'C1', 'label_el': 'Φορτηγό έως 7.5 τόνους', 'label_en': 'Truck up to 7.5t', 'display_order': 7},
        {'code': 'C1E', 'label_el': 'Φορτηγό έως 7.5t με ρυμουλκούμενο', 'label_en': 'Truck up to 7.5t with Trailer', 'display_order': 8},
        {'code': 'C', 'label_el': 'Φορτηγό', 'label_en': 'Truck', 'display_order': 9},
        {'code': 'CE', 'label_el': 'Φορτηγό με ρυμουλκούμενο', 'label_en': 'Truck with Trailer', 'display_order': 10},
        {'code': 'D1', 'label_el': 'Λεωφορείο έως 16 θέσεις', 'label_en': 'Bus up to 16 seats', 'display_order': 11},
        {'code': 'D1E', 'label_el': 'Λεωφορείο έως 16 θέσεις με ρυμουλκούμενο', 'label_en': 'Bus up to 16 seats with Trailer', 'display_order': 12},
        {'code': 'D', 'label_el': 'Λεωφορείο', 'label_en': 'Bus', 'display_order': 13},
        {'code': 'DE', 'label_el': 'Λεωφορείο με ρυμουλκούμενο', 'label_en': 'Bus with Trailer', 'display_order': 14},
    ]
    
    for cat in categories:
        DrivingLicenseCategory.objects.create(**cat)


def seed_adr_categories(apps, schema_editor):
    """Seed ADR categories for dangerous goods"""
    AdrCategory = apps.get_model('core', 'AdrCategory')
    
    categories = [
        {'code': 'Π1', 'label_el': 'Εκρηκτικά', 'label_en': 'Explosives', 'display_order': 1},
        {'code': 'Π2', 'label_el': 'Αέρια', 'label_en': 'Gases', 'display_order': 2},
        {'code': 'Π3', 'label_el': 'Εύφλεκτα υγρά', 'label_en': 'Flammable Liquids', 'display_order': 3},
        {'code': 'Π4', 'label_el': 'Εύφλεκτα στερεά', 'label_en': 'Flammable Solids', 'display_order': 4},
        {'code': 'Π5', 'label_el': 'Οξειδωτικές ουσίες', 'label_en': 'Oxidizing Substances', 'display_order': 5},
        {'code': 'Π6', 'label_el': 'Τοξικές ουσίες', 'label_en': 'Toxic Substances', 'display_order': 6},
        {'code': 'Π7', 'label_el': 'Ραδιενεργά υλικά', 'label_en': 'Radioactive Materials', 'display_order': 7},
        {'code': 'Π8', 'label_el': 'Διαβρωτικές ουσίες', 'label_en': 'Corrosive Substances', 'display_order': 8},
        {'code': 'Π9', 'label_el': 'Διάφορες επικίνδυνες ουσίες', 'label_en': 'Miscellaneous Dangerous Substances', 'display_order': 9},
    ]
    
    for cat in categories:
        AdrCategory.objects.create(**cat)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_delete_driverprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdrCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='π.χ. Π1, Π2, Π3, Π4, Π5, Π6, Π7, Π8, Π9', max_length=10, unique=True, verbose_name='Κωδικός ADR')),
                ('label_el', models.CharField(max_length=200, verbose_name='Ελληνική Περιγραφή')),
                ('label_en', models.CharField(max_length=200, verbose_name='Αγγλική Περιγραφή')),
                ('display_order', models.IntegerField(default=0, verbose_name='Σειρά Εμφάνισης')),
            ],
            options={
                'verbose_name': 'Κατηγορία ADR',
                'verbose_name_plural': 'Κατηγορίες ADR',
                'ordering': ['display_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='DrivingLicenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='π.χ. B, C, CE, D, DE', max_length=10, unique=True, verbose_name='Κωδικός Κατηγορίας')),
                ('label_el', models.CharField(max_length=100, verbose_name='Ελληνική Ονομασία')),
                ('label_en', models.CharField(max_length=100, verbose_name='Αγγλική Ονομασία')),
                ('display_order', models.IntegerField(default=0, verbose_name='Σειρά Εμφάνισης')),
            ],
            options={
                'verbose_name': 'Κατηγορία Άδειας Οδήγησης',
                'verbose_name_plural': 'Κατηγορίες Αδειών Οδήγησης',
                'ordering': ['display_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='DriverCompliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=20, verbose_name='Αριθμός Άδειας Οδήγησης')),
                ('license_issue_date', models.DateField(blank=True, null=True, verbose_name='Ημερομηνία Έκδοσης Άδειας')),
                ('license_expiry_date', models.DateField(verbose_name='Ημερομηνία Λήξης Άδειας')),
                ('pei_truck_expiry', models.DateField(blank=True, help_text='Πιστοποιητικό Επαγγελματικής Ικανότητας για φορτηγά', null=True, verbose_name='Λήξη ΠΕΙ Φορτηγών')),
                ('pei_bus_expiry', models.DateField(blank=True, help_text='Πιστοποιητικό Επαγγελματικής Ικανότητας για λεωφορεία', null=True, verbose_name='Λήξη ΠΕΙ Λεωφορείων')),
                ('tachograph_card_number', models.CharField(blank=True, max_length=20, verbose_name='Αριθμός Κάρτας Ψηφιακού Ταχογράφου')),
                ('tachograph_card_expiry', models.DateField(blank=True, null=True, verbose_name='Λήξη Κάρτας Ταχογράφου')),
                ('adr_expiry', models.DateField(blank=True, null=True, verbose_name='Λήξη ADR')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adr_categories', models.ManyToManyField(blank=True, help_text='Πιστοποίηση μεταφοράς επικίνδυνων εμπορευμάτων', related_name='drivers', to='core.adrcategory', verbose_name='Κατηγορίες ADR')),
                ('employee', models.OneToOneField(limit_choices_to={'position__is_driver_role': True}, on_delete=django.db.models.deletion.CASCADE, related_name='driver_compliance', to='core.employee', verbose_name='Υπάλληλος')),
                ('license_categories', models.ManyToManyField(help_text='π.χ. B, C, CE, D, DE', related_name='drivers', to='core.drivinglicensecategory', verbose_name='Κατηγορίες Άδειας')),
            ],
            options={
                'verbose_name': 'Συμμόρφωση Οδηγού',
                'verbose_name_plural': 'Συμμορφώσεις Οδηγών',
                'ordering': ['employee__last_name', 'employee__first_name'],
            },
        ),
        # Seed lookup tables
        migrations.RunPython(seed_license_categories, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(seed_adr_categories, reverse_code=migrations.RunPython.noop),
    ]
