# Generated by Django 5.0.2 on 2026-02-11 22:00

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_taxi_remove_bus_has_ac_remove_bus_has_wifi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalOverhead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Έτος')),
                ('annual_rent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Ετήσιο Ενοίκιο (€)')),
                ('annual_utilities', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Ετήσια Κοινόχρηστα (€)')),
                ('office_salaries_gross', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Λογιστές, Διαχειριστές, κλπ', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Μισθοδοσία Γραφείου (€)')),
                ('software_subscriptions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Συνδρομές Λογισμικού (€)')),
                ('marketing_costs', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Κόστη Marketing (€)')),
                ('owner_opportunity_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Opportunity cost - τι θα έπαιρνε ως υπάλληλος', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Τεκμαρτός Μισθός Ιδιοκτήτη (€)')),
                ('notes', models.TextField(blank=True, verbose_name='Σημειώσεις')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overheads', to='core.company', verbose_name='Εταιρεία')),
            ],
            options={
                'verbose_name': 'Γενικά Έξοδα',
                'verbose_name_plural': 'Γενικά Έξοδα',
                'ordering': ['-year'],
                'unique_together': {('company', 'year')},
            },
        ),
        migrations.CreateModel(
            name='TransportOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200, verbose_name='Όνομα Πελάτη')),
                ('date', models.DateField(verbose_name='Ημερομηνία')),
                ('origin', models.CharField(max_length=200, verbose_name='Αφετηρία')),
                ('destination', models.CharField(max_length=200, verbose_name='Προορισμός')),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Απόσταση (km)')),
                ('agreed_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Συμφωνημένη Τιμή (€)')),
                ('duration_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Διάρκεια (ώρες)')),
                ('tolls_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Διόδια (€)')),
                ('ferry_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Πορθμείο (€)')),
                ('status', models.CharField(choices=[('PENDING', 'Εκκρεμεί'), ('IN_PROGRESS', 'Σε Εξέλιξη'), ('COMPLETED', 'Ολοκληρώθηκε'), ('INVOICED', 'Τιμολογήθηκε')], default='PENDING', max_length=20, verbose_name='Κατάσταση')),
                ('notes', models.TextField(blank=True, verbose_name='Σημειώσεις')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transport_orders', to='core.driverprofile', verbose_name='Οδηγός')),
                ('assigned_vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transport_orders', to='core.vehicleasset', verbose_name='Όχημα')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_orders', to='core.company', verbose_name='Εταιρεία')),
            ],
            options={
                'verbose_name': 'Εντολή Μεταφοράς',
                'verbose_name_plural': 'Εντολές Μεταφοράς',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['company', '-date'], name='finance_tra_company_54eeba_idx'), models.Index(fields=['assigned_vehicle', '-date'], name='finance_tra_assigne_ccd49a_idx'), models.Index(fields=['status'], name='finance_tra_status_3de92d_idx')],
            },
        ),
    ]
