# Generated by Django 5.0.2 on 2026-02-12 07:30

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_taxi_remove_bus_has_ac_remove_bus_has_wifi_and_more'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Κατηγορία')),
                ('description', models.TextField(blank=True, verbose_name='Περιγραφή')),
                ('is_system_default', models.BooleanField(default=False, help_text='Κατηγορίες που δημιουργούνται αυτόματα από το σύστημα', verbose_name='Προεπιλεγμένη Κατηγορία')),
            ],
            options={
                'verbose_name': 'Κατηγορία Εξόδου',
                'verbose_name_plural': 'Κατηγορίες Εξόδων',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Όνομα Κέντρου Κόστους')),
                ('description', models.TextField(blank=True, verbose_name='Περιγραφή')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ενεργό')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_centers', to='core.company', verbose_name='Εταιρεία')),
            ],
            options={
                'verbose_name': 'Κέντρο Κόστους',
                'verbose_name_plural': 'Κέντρα Κόστους',
                'ordering': ['company', 'name'],
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.CreateModel(
            name='RecurringExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Ποσό (€)')),
                ('frequency', models.CharField(choices=[('MONTHLY', 'Μηνιαίο'), ('BI_MONTHLY', 'Διμηνιαίο'), ('QUARTERLY', 'Τριμηνιαίο'), ('SEMI_ANNUAL', 'Εξαμηνιαίο'), ('ANNUAL', 'Ετήσιο')], default='MONTHLY', max_length=20, verbose_name='Συχνότητα')),
                ('description', models.TextField(blank=True, verbose_name='Περιγραφή')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ενεργό')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Ημ/νία Έναρξης')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Ημ/νία Λήξης')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='finance.expensecategory', verbose_name='Κατηγορία')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_expenses', to='core.company', verbose_name='Εταιρεία')),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='finance.costcenter', verbose_name='Κέντρο Κόστους')),
            ],
            options={
                'verbose_name': 'Περιοδικό Έξοδο',
                'verbose_name_plural': 'Περιοδικά Έξοδα',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='GlobalOverhead',
        ),
        migrations.AddIndex(
            model_name='recurringexpense',
            index=models.Index(fields=['company', 'is_active'], name='finance_rec_company_939d41_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringexpense',
            index=models.Index(fields=['category'], name='finance_rec_categor_0b4a39_idx'),
        ),
    ]
