# Generated by Django 5.0.2 on 2026-02-13 05:17

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_taxi_remove_bus_has_ac_remove_bus_has_wifi_and_more'),
        ('finance', '0002_expensecategory_costcenter_recurringexpense_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Οικογένεια Εξόδων')),
                ('icon', models.CharField(default='folder', help_text="e.g., 'building', 'wifi', 'users', 'file-invoice'", max_length=50, verbose_name='Font Awesome Icon')),
                ('description', models.TextField(blank=True, verbose_name='Περιγραφή')),
                ('display_order', models.IntegerField(default=0, verbose_name='Σειρά Εμφάνισης')),
            ],
            options={
                'verbose_name': 'Οικογένεια Εξόδων',
                'verbose_name_plural': 'Οικογένειες Εξόδων',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='expensecategory',
            options={'ordering': ['family', 'name'], 'verbose_name': 'Κατηγορία Εξόδου', 'verbose_name_plural': 'Κατηγορίες Εξόδων'},
        ),
        migrations.CreateModel(
            name='CompanyExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Ποσό (€)')),
                ('start_date', models.DateField(verbose_name='Ημ/νία Έναρξης')),
                ('end_date', models.DateField(blank=True, help_text='Αν κενό, το έξοδο είναι ανοιχτό (recurring)', null=True, verbose_name='Ημ/νία Λήξης')),
                ('is_amortized', models.BooleanField(default=False, help_text='Αν True, το κόστος κατανέμεται ημερησίως στο διάστημα start_date - end_date', verbose_name='Αποσβέσιμο')),
                ('invoice_number', models.CharField(blank=True, max_length=100, verbose_name='Αριθμός Τιμολογίου')),
                ('description', models.TextField(blank=True, verbose_name='Περιγραφή')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ενεργό')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='company_expenses', to='finance.expensecategory', verbose_name='Κατηγορία')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_expenses', to='core.company', verbose_name='Εταιρεία')),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_expenses', to='finance.costcenter', verbose_name='Κέντρο Κόστους')),
            ],
            options={
                'verbose_name': 'Έξοδο Εταιρείας',
                'verbose_name_plural': 'Έξοδα Εταιρείας',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='finance.expensefamily', verbose_name='Οικογένεια'),
        ),
        migrations.DeleteModel(
            name='RecurringExpense',
        ),
        migrations.AddIndex(
            model_name='companyexpense',
            index=models.Index(fields=['company', 'is_active'], name='finance_com_company_7376b3_idx'),
        ),
        migrations.AddIndex(
            model_name='companyexpense',
            index=models.Index(fields=['category'], name='finance_com_categor_88b5a4_idx'),
        ),
        migrations.AddIndex(
            model_name='companyexpense',
            index=models.Index(fields=['start_date', 'end_date'], name='finance_com_start_d_e10ec1_idx'),
        ),
    ]
