# Generated by Django 5.0.2 on 2026-02-13 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_expensefamily_alter_expensecategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensecategory',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='finance.expensefamily', verbose_name='Οικογένεια'),
        ),
    ]
