# Generated by Django 5.0.14 on 2026-02-13 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_expensecategory_family'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyexpense',
            name='expense_type',
            field=models.CharField(choices=[('RECURRING', 'Τακτικό'), ('ONE_OFF', 'Έκτακτο')], default='RECURRING', max_length=20, verbose_name='Τύπος Εξόδου'),
        ),
        migrations.AddField(
            model_name='companyexpense',
            name='periodicity',
            field=models.CharField(choices=[('MONTHLY', 'Μηνιαίο'), ('YEARLY', 'Ετήσιο'), ('NONE', 'Εφάπαξ')], default='MONTHLY', max_length=20, verbose_name='Περιοδικότητα'),
        ),
    ]
