# Generated by Django 5.0.14 on 2026-02-13 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_companyexpense_expense_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyexpense',
            name='is_amortized',
            field=models.BooleanField(default=False, help_text='π.χ. Ένα ετήσιο έξοδο 120€ θα υπολογίζεται ως 10€/μήνα', verbose_name='Κατανομή σε μήνες'),
        ),
        migrations.AlterField(
            model_name='companyexpense',
            name='periodicity',
            field=models.CharField(choices=[('MONTHLY', 'Μηνιαίο'), ('QUARTERLY', 'Τριμηνιαίο'), ('BIANNUAL', 'Εξαμηνιαίο'), ('YEARLY', 'Ετήσιο'), ('NONE', 'Εφάπαξ')], default='MONTHLY', max_length=20, verbose_name='Περιοδικότητα'),
        ),
    ]
