# Generated by Django 5.0.14 on 2026-02-13 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_alter_companyexpense_is_amortized_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyexpense',
            name='distribute_to_all_centers',
            field=models.BooleanField(default=False, help_text='Αν επιλεγεί, το κόστος θα μοιραστεί ισόποσα σε όλα τα ενεργά κέντρα κόστους', verbose_name='Επιμερισμός σε όλα τα κέντρα'),
        ),
    ]
