# Generated by Django 5.0.14 on 2026-02-13 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_employeeposition_employee'),
        ('finance', '0007_companyexpense_distribute_to_all_centers'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyexpense',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='core.employee', verbose_name='Υπάλληλος'),
        ),
    ]
