# Generated by Django 5.0.14 on 2026-02-14 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_company_transport_type_and_more'),
        ('finance', '0008_companyexpense_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensecategory',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Αν NULL, είναι προεπιλεγμένη κατηγορία. Αν έχει εταιρεία, είναι προσαρμοσμένη.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_categories', to='core.company', verbose_name='Εταιρεία'),
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Κατηγορία'),
        ),
        migrations.AlterUniqueTogether(
            name='expensecategory',
            unique_together={('company', 'name')},
        ),
    ]
