# Generated by Django 5.0.14 on 2026-02-14 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_expensecategory_company_alter_expensecategory_name_and_more'),
        ('operations', '0003_alter_vehicle_options_vehicle_adr_expiry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportorder',
            name='assigned_vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transport_orders', to='operations.vehicle', verbose_name='Όχημα'),
        ),
    ]
