# Generated by Django 5.0.2 on 2026-02-18 05:04

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_company_utilization_rate_and_more'),
        ('finance', '0010_alter_transportorder_assigned_vehicle'),
        ('operations', '0006_vehicle_average_fuel_consumption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='costcenter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='costcenter',
            name='driver',
            field=models.ForeignKey(blank=True, help_text='Σύνδεση με οδηγό για αυτόματη κατανομή', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_center', to='core.driverprofile', verbose_name='Οδηγός'),
        ),
        migrations.AddField(
            model_name='costcenter',
            name='type',
            field=models.CharField(choices=[('VEHICLE', 'Όχημα'), ('DRIVER', 'Οδηγός'), ('OVERHEAD', 'Γενικά Έξοδα'), ('ROUTE', 'Διαδρομή'), ('OTHER', 'Άλλο')], default='OTHER', max_length=20, verbose_name='Τύπος Κέντρου'),
        ),
        migrations.AddField(
            model_name='costcenter',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='costcenter',
            name='vehicle',
            field=models.ForeignKey(blank=True, help_text='Σύνδεση με όχημα για αυτόματη κατανομή', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_center', to='operations.vehicle', verbose_name='Όχημα'),
        ),
        migrations.CreateModel(
            name='CostItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Όνομα Κόστους')),
                ('description', models.TextField(blank=True, verbose_name='Περιγραφή')),
                ('category', models.CharField(choices=[('FIXED', 'Σταθερό'), ('VARIABLE', 'Μεταβλητό'), ('INDIRECT', 'Έμμεσο')], max_length=20, verbose_name='Κατηγορία Κόστους')),
                ('unit', models.CharField(choices=[('MONTH', 'Μήνας'), ('KM', 'Χιλιόμετρο'), ('HOUR', 'Ώρα'), ('TRIP', 'Δρομολόγιο')], max_length=20, verbose_name='Μονάδα Μέτρησης')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ενεργό')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_items', to='core.company', verbose_name='Εταιρεία')),
            ],
            options={
                'verbose_name': 'Στοιχείο Κόστους',
                'verbose_name_plural': 'Στοιχεία Κόστους',
                'ordering': ['company', 'category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CostPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Ποσό (€)')),
                ('period_start', models.DateField(verbose_name='Έναρξη Περιόδου')),
                ('period_end', models.DateField(verbose_name='Λήξη Περιόδου')),
                ('notes', models.TextField(blank=True, verbose_name='Σημειώσεις')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_postings', to='core.company', verbose_name='Εταιρεία')),
                ('cost_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_postings', to='finance.costcenter', verbose_name='Κέντρο Κόστους')),
                ('cost_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cost_postings', to='finance.costitem', verbose_name='Στοιχείο Κόστους')),
            ],
            options={
                'verbose_name': 'Καταχώρηση Κόστους',
                'verbose_name_plural': 'Καταχωρήσεις Κόστους',
                'ordering': ['-period_start', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='costitem',
            index=models.Index(fields=['company', 'category'], name='finance_cos_company_467bfc_idx'),
        ),
        migrations.AddIndex(
            model_name='costitem',
            index=models.Index(fields=['is_active'], name='finance_cos_is_acti_8201af_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='costitem',
            unique_together={('company', 'name')},
        ),
        migrations.AddIndex(
            model_name='costposting',
            index=models.Index(fields=['company', '-period_start'], name='finance_cos_company_f9d820_idx'),
        ),
        migrations.AddIndex(
            model_name='costposting',
            index=models.Index(fields=['cost_center', '-period_start'], name='finance_cos_cost_ce_bb6799_idx'),
        ),
        migrations.AddIndex(
            model_name='costposting',
            index=models.Index(fields=['cost_item'], name='finance_cos_cost_it_61be8e_idx'),
        ),
    ]
