# Generated by Django 5.0.14 on 2026-02-19 13:15

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_company_utilization_rate_and_more'),
        ('finance', '0011_costcenter_created_at_costcenter_driver_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderCostBreakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(verbose_name='Έναρξη Περιόδου')),
                ('period_end', models.DateField(verbose_name='Λήξη Περιόδου')),
                ('vehicle_alloc', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Κατανομή Οχήματος (€)')),
                ('overhead_alloc', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Κατανομή Γενικών Εξόδων (€)')),
                ('direct_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Άμεσο Κόστος (€)')),
                ('total_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Συνολικό Κόστος (€)')),
                ('revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Έσοδα (€)')),
                ('profit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Κέρδος (€)')),
                ('margin', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=7, verbose_name='Περιθώριο (%)')),
                ('status', models.CharField(choices=[('OK', 'OK'), ('MISSING_RATE', 'Λείπει Τιμή')], default='OK', max_length=20, verbose_name='Κατάσταση')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_cost_breakdowns', to='core.company', verbose_name='Εταιρεία')),
                ('transport_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_breakdown', to='finance.transportorder', verbose_name='Εντολή Μεταφοράς')),
            ],
            options={
                'verbose_name': 'Ανάλυση Κόστους Εντολής',
                'verbose_name_plural': 'Αναλύσεις Κόστους Εντολών',
                'ordering': ['-period_start', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CostRateSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(verbose_name='Έναρξη Περιόδου')),
                ('period_end', models.DateField(verbose_name='Λήξη Περιόδου')),
                ('basis_unit', models.CharField(choices=[('KM', 'Χιλιόμετρο'), ('HOUR', 'Ώρα'), ('TRIP', 'Δρομολόγιο'), ('REVENUE', 'Έσοδα')], max_length=20, verbose_name='Μονάδα Βάσης')),
                ('total_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Συνολικό Κόστος (€)')),
                ('total_units', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12, verbose_name='Συνολικές Μονάδες')),
                ('rate', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=12, verbose_name='Τιμή ανά Μονάδα (€)')),
                ('status', models.CharField(choices=[('OK', 'OK'), ('MISSING_ACTIVITY', 'Χωρίς Δραστηριότητα')], default='OK', max_length=20, verbose_name='Κατάσταση')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_rate_snapshots', to='core.company', verbose_name='Εταιρεία')),
                ('cost_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_snapshots', to='finance.costcenter', verbose_name='Κέντρο Κόστους')),
            ],
            options={
                'verbose_name': 'Στιγμιότυπο Τιμής Κόστους',
                'verbose_name_plural': 'Στιγμιότυπα Τιμών Κόστους',
                'ordering': ['-period_start', '-created_at'],
                'indexes': [models.Index(fields=['company', '-period_start'], name='finance_cos_company_3ee550_idx'), models.Index(fields=['cost_center', '-period_start'], name='finance_cos_cost_ce_de5730_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='costratesnapshot',
            constraint=models.UniqueConstraint(fields=('company', 'period_start', 'period_end', 'cost_center', 'basis_unit'), name='unique_cost_rate_snapshot'),
        ),
        migrations.AddIndex(
            model_name='ordercostbreakdown',
            index=models.Index(fields=['company', '-period_start'], name='finance_ord_company_c31144_idx'),
        ),
        migrations.AddIndex(
            model_name='ordercostbreakdown',
            index=models.Index(fields=['transport_order'], name='finance_ord_transpo_d72db8_idx'),
        ),
        migrations.AddConstraint(
            model_name='ordercostbreakdown',
            constraint=models.UniqueConstraint(fields=('company', 'transport_order', 'period_start', 'period_end'), name='unique_order_cost_breakdown'),
        ),
    ]
