# Generated by Django 5.0.14 on 2026-02-26 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_employee_vehicle_add_personnel_driver_fields'),
        ('finance', '0012_ordercostbreakdown_costratesnapshot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportorder',
            name='assigned_driver',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'position__is_driver_role': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transport_orders', to='core.employee', verbose_name='Οδηγός'),
        ),
    ]
