# Generated by Django 5.0.14 on 2026-02-27 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_employee_vehicle_add_personnel_driver_fields'),
        ('finance', '0013_change_transportorder_driver_to_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costcenter',
            name='driver',
            field=models.ForeignKey(blank=True, help_text='Σύνδεση με οδηγό για αυτόματη κατανομή', limit_choices_to={'is_active': True, 'position__is_driver_role': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_centers_as_driver', to='core.employee', verbose_name='Οδηγός'),
        ),
    ]
