# Generated by Django 5.0.14 on 2026-02-28 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_costcenter_driver_to_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportorder',
            name='requires_adr',
            field=models.BooleanField(default=False, help_text='Μεταφορά επικίνδυνων εμπορευμάτων', verbose_name='Απαιτεί ADR'),
        ),
    ]
