# Generated by Django 5.0.2 on 2026-02-11 21:54

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_taxi_remove_bus_has_ac_remove_bus_has_wifi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Ημερομηνία')),
                ('fuel_station_name', models.CharField(blank=True, max_length=100, verbose_name='Πρατήριο')),
                ('liters', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Λίτρα')),
                ('cost_per_liter', models.DecimalField(decimal_places=3, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Τιμή/Λίτρο (€)')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Συνολικό Κόστος (€)')),
                ('is_full_tank', models.BooleanField(default=False, help_text='Κρίσιμο για ακριβή υπολογισμό κατανάλωσης', verbose_name='Γέμισμα Ρεζερβουάρ')),
                ('odometer_reading', models.PositiveIntegerField(verbose_name='Ένδειξη Χιλιομετρητή')),
                ('adblue_liters', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='AdBlue Λίτρα')),
                ('adblue_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='AdBlue Κόστος (€)')),
                ('notes', models.TextField(blank=True, verbose_name='Σημειώσεις')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_entries', to='core.company', verbose_name='Εταιρεία')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuel_entries', to='core.driverprofile', verbose_name='Οδηγός')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_entries', to='core.vehicleasset', verbose_name='Όχημα')),
            ],
            options={
                'verbose_name': 'Καταχώρηση Καυσίμου',
                'verbose_name_plural': 'Καταχωρήσεις Καυσίμων',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['vehicle', '-date'], name='operations__vehicle_5b6a46_idx'), models.Index(fields=['company', '-date'], name='operations__company_0ca329_idx')],
            },
        ),
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Ημερομηνία')),
                ('type', models.CharField(choices=[('ACCIDENT', 'Ατύχημα'), ('FINE', 'Κλήση Τροχαίας'), ('BREAKDOWN', 'Βλάβη')], max_length=20, verbose_name='Τύπος Συμβάντος')),
                ('location', models.CharField(max_length=200, verbose_name='Τοποθεσία')),
                ('description', models.TextField(verbose_name='Περιγραφή')),
                ('cost_estimate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Εκτίμηση Κόστους (€)')),
                ('police_report_number', models.CharField(blank=True, max_length=50, verbose_name='Αριθμός Δελτίου Τροχαίας')),
                ('photos', models.FileField(blank=True, null=True, upload_to='incident_photos/%Y/%m/', verbose_name='Φωτογραφίες')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Επιλύθηκε')),
                ('resolution_notes', models.TextField(blank=True, verbose_name='Σημειώσεις Επίλυσης')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='core.company', verbose_name='Εταιρεία')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='core.driverprofile', verbose_name='Οδηγός')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='core.vehicleasset', verbose_name='Όχημα')),
            ],
            options={
                'verbose_name': 'Αναφορά Συμβάντος',
                'verbose_name_plural': 'Αναφορές Συμβάντων',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['vehicle', '-date'], name='operations__vehicle_76c08b_idx'), models.Index(fields=['company', '-date'], name='operations__company_50dcee_idx'), models.Index(fields=['type', 'is_resolved'], name='operations__type_800bb1_idx')],
            },
        ),
        migrations.CreateModel(
            name='ServiceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Ημερομηνία')),
                ('service_type', models.CharField(choices=[('REGULAR', 'Τακτική Συντήρηση'), ('REPAIR', 'Επισκευή'), ('TIRE_CHANGE', 'Αλλαγή Ελαστικών'), ('KTEO', 'Έλεγχος ΚΤΕΟ'), ('TACHOGRAPH', 'Βαθμονόμηση Ταχογράφου')], max_length=20, verbose_name='Τύπος Εργασίας')),
                ('odometer_reading', models.PositiveIntegerField(verbose_name='Ένδειξη Χιλιομετρητή')),
                ('cost_parts', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Κόστος Ανταλλακτικών (€)')),
                ('cost_labor', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Κόστος Εργασίας (€)')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Συνολικό Κόστος (€)')),
                ('description', models.TextField(verbose_name='Περιγραφή Εργασιών')),
                ('invoice_number', models.CharField(blank=True, max_length=50, verbose_name='Αριθμός Τιμολογίου')),
                ('invoice_attachment', models.FileField(blank=True, null=True, upload_to='service_invoices/%Y/%m/', verbose_name='Συνημμένο Τιμολόγιο')),
                ('notes', models.TextField(blank=True, verbose_name='Σημειώσεις Μηχανικού')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_logs', to='core.company', verbose_name='Εταιρεία')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_logs', to='core.vehicleasset', verbose_name='Όχημα')),
            ],
            options={
                'verbose_name': 'Καταχώρηση Συντήρησης',
                'verbose_name_plural': 'Καταχωρήσεις Συντήρησης',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['vehicle', '-date'], name='operations__vehicle_85be07_idx'), models.Index(fields=['company', '-date'], name='operations__company_5fb9e0_idx'), models.Index(fields=['service_type'], name='operations__service_e961b7_idx')],
            },
        ),
    ]
