# Generated by Django 5.0.14 on 2026-02-13 18:49

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_company_transport_type_and_more'),
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=20, unique=True, verbose_name='Πινακίδα')),
                ('make', models.CharField(max_length=50, verbose_name='Μάρκα')),
                ('model', models.CharField(max_length=50, verbose_name='Μοντέλο')),
                ('vehicle_type', models.CharField(choices=[('TRUCK', 'Φορτηγό'), ('BUS', 'Λεωφορείο'), ('VAN', 'Van'), ('CAR', 'Αυτοκίνητο')], max_length=20, verbose_name='Τύπος Οχήματος')),
                ('gross_weight_kg', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Μικτό Βάρος (kg)')),
                ('payload_capacity_kg', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ωφέλιμο Φορτίο (kg)')),
                ('seats', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Θέσεις Επιβατών')),
                ('purchase_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Αξία Αγοράς (€)')),
                ('residual_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Υπολειμματική Αξία (€)')),
                ('depreciation_years', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Έτη Απόσβεσης')),
                ('annual_insurance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Ετήσια Ασφάλιση (€)')),
                ('annual_road_tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Ετήσια Τέλη Κυκλοφορίας (€)')),
                ('available_hours_per_year', models.IntegerField(default=1936, help_text='1936 ώρες = 11 μήνες × 22 ημέρες × 8 ώρες', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Διαθέσιμες Ώρες/Έτος')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fleet_vehicles', to='core.company', verbose_name='Εταιρεία')),
            ],
            options={
                'verbose_name': 'Όχημα (Λογιστικό)',
                'verbose_name_plural': 'Οχήματα (Λογιστικά)',
                'ordering': ['license_plate'],
            },
        ),
    ]
