# Generated by Django 5.0.14 on 2026-02-14 11:43

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_moto_vehicleasset_ptr_and_more'),
        ('operations', '0002_vehicle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ['license_plate'], 'verbose_name': 'Όχημα', 'verbose_name_plural': 'Οχήματα'},
        ),
        migrations.AddField(
            model_name='vehicle',
            name='adr_expiry',
            field=models.DateField(blank=True, help_text='Μόνο για οχήματα επικίνδυνων φορτίων', null=True, verbose_name='Λήξη ADR'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='color',
            field=models.CharField(blank=True, max_length=30, verbose_name='Χρώμα'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='current_odometer',
            field=models.PositiveIntegerField(default=0, verbose_name='Τρέχοντα Χιλιόμετρα'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(choices=[('DIESEL', 'Πετρέλαιο'), ('PETROL', 'Βενζίνη'), ('ELECTRIC', 'Ηλεκτρικό'), ('GAS', 'Φυσικό Αέριο (CNG/LNG)'), ('HYBRID', 'Υβριδικό')], default='DIESEL', max_length=20, verbose_name='Τύπος Καυσίμου'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='height_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Ύψος (m)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='insurance_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='Λήξη Ασφάλισης'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='kteo_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='Λήξη ΚΤΕΟ'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='last_service_km',
            field=models.PositiveIntegerField(default=0, verbose_name='Χιλιόμετρα Τελευταίας Συντήρησης'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='length_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Μήκος (m)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='manufacturing_year',
            field=models.PositiveIntegerField(default=2020, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)], verbose_name='Έτος Κατασκευής'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Σημειώσεις'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Ενεργό'), ('MAINTENANCE', 'Σε Συντήρηση'), ('INACTIVE', 'Ανενεργό'), ('SOLD', 'Πωλήθηκε')], default='ACTIVE', max_length=20, verbose_name='Κατάσταση'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='tank_capacity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Χωρητικότητα Ρεζερβουάρ (L/kWh)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vin',
            field=models.CharField(blank=True, max_length=17, null=True, unique=True, verbose_name='Αριθμός Πλαισίου (VIN)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='width_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Πλάτος (m)'),
        ),
        migrations.AlterField(
            model_name='fuelentry',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_entries', to='operations.vehicle', verbose_name='Όχημα'),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='operations.vehicle', verbose_name='Όχημα'),
        ),
        migrations.AlterField(
            model_name='servicelog',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_logs', to='operations.vehicle', verbose_name='Όχημα'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='seats',
            field=models.IntegerField(blank=True, help_text='0 για φορτηγά, >0 για επιβατικά', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Θέσεις Επιβατών'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('TRUCK', 'Φορτηγό'), ('BUS', 'Λεωφορείο'), ('VAN', 'Van'), ('CAR', 'Αυτοκίνητο'), ('MOTO', 'Μοτοσυκλέτα')], max_length=20, verbose_name='Τύπος Οχήματος'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['company', 'status'], name='operations__company_52fcc5_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['vehicle_type'], name='operations__vehicle_b29bd0_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['license_plate'], name='operations__license_d6df92_idx'),
        ),
    ]
