# Generated by Django 5.0.14 on 2026-02-15 14:24

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_delete_vehicleasset'),
        ('operations', '0003_alter_vehicle_options_vehicle_adr_expiry_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='vehicle',
            name='operations__vehicle_b29bd0_idx',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='annual_insurance',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='annual_road_tax',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='length_m',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='payload_capacity_kg',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_type',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='body_type',
            field=models.CharField(choices=[('TRACTOR_UNIT', 'Μονάδα Ελκυστήρα (Tractor Unit)'), ('CURTAIN', 'Κουρτίνα (Curtain Sider)'), ('BOX', 'Κόφα (Box/Van Body)'), ('FLATBED', 'Πλατφόρμα/Ανοιχτό (Flatbed)'), ('REFRIGERATOR', 'Ψυγείο (Refrigerated)'), ('TANKER', 'Βυτίο (Tanker)'), ('TIPPER', 'Ανατρεπόμενο (Tipper/Dump)'), ('CONTAINER_CHASSIS', 'Βάση Κοντέινερ (Container Chassis)'), ('CAR_CARRIER', 'Αυτοκινητάμαξα (Car Carrier)'), ('BUS_BODY', 'Αμάξωμα Λεωφορείου (Bus Body)'), ('OTHER', 'Άλλο / Ειδικό (Other/Special)')], default='OTHER', help_text='Φυσική διαμόρφωση χώρου φορτίου', max_length=30, verbose_name='Τύπος Αμαξώματος'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='emission_class',
            field=models.CharField(blank=True, choices=[('EURO_3', 'Euro 3'), ('EURO_4', 'Euro 4'), ('EURO_5', 'Euro 5'), ('EURO_6', 'Euro 6'), ('EURO_6C', 'Euro 6c'), ('EURO_6D', 'Euro 6d'), ('ELECTRIC_ZERO', 'Μηδενικές Εκπομπές (Electric/Zero)')], help_text='Κρίσιμο για διεθνή διόδια και περιβαλλοντικές ζώνες', max_length=20, null=True, verbose_name='Κατηγορία Εκπομπών (Euro)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='horsepower',
            field=models.IntegerField(blank=True, help_text='Για ελκυστήρες, φορτηγά, λεωφορεία', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Ιπποδύναμη (HP)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='length_total_m',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Συμπεριλαμβανομένων προεξοχών', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Συνολικό Μήκος (m)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='pallets_capacity',
            field=models.IntegerField(blank=True, help_text='Προαιρετικό - για φορτηγά', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Χωρητικότητα Παλετών'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='unladen_weight_kg',
            field=models.IntegerField(blank=True, help_text='Βάρος κενού οχήματος', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Απόβαρο (kg)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_class',
            field=models.CharField(choices=[('TRACTOR', 'Ελκυστήρας (Tractor)'), ('TRUCK', 'Φορτηγό (Rigid Truck)'), ('SEMI_TRAILER', 'Ημιρυμουλκούμενο (Semi-Trailer)'), ('TRAILER', 'Ρυμουλκούμενο (Trailer)'), ('BUS', 'Λεωφορείο (Bus)'), ('VAN', 'Βαν / Ελαφρύ Φορτηγό (Van)'), ('CAR', 'Επιβατικό (Passenger Car)')], default='TRUCK', help_text='Καθορίζει τις λειτουργικές δυνατότητες', max_length=20, verbose_name='Κλάση Οχήματος'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(choices=[('DIESEL', 'Πετρέλαιο (Diesel)'), ('PETROL', 'Βενζίνη (Petrol/Gasoline)'), ('ELECTRIC', 'Ηλεκτρικό (Electric)'), ('GAS', 'Φυσικό Αέριο (CNG/LNG)'), ('HYBRID', 'Υβριδικό (Hybrid)')], default='DIESEL', max_length=20, verbose_name='Τύπος Καυσίμου'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='gross_weight_kg',
            field=models.IntegerField(blank=True, help_text='Μέγιστο επιτρεπόμενο βάρος (από άδεια κυκλοφορίας)', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Μικτό Βάρος (kg)'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='height_m',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Κρίσιμο για γέφυρες και σήραγγες', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Ύψος (m)'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='license_plate',
            field=models.CharField(max_length=20, unique=True, verbose_name='Πινακίδα Κυκλοφορίας'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='make',
            field=models.CharField(max_length=50, verbose_name='Μάρκα (Make)'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.CharField(max_length=50, verbose_name='Μοντέλο (Model)'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='seats',
            field=models.IntegerField(blank=True, help_text='Για λεωφορεία και επιβατικά', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Θέσεις Επιβατών'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vin',
            field=models.CharField(blank=True, help_text='17-ψήφιος κωδικός πλαισίου', max_length=17, null=True, unique=True, verbose_name='Αριθμός Πλαισίου (VIN/Chassis No)'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['vehicle_class'], name='operations__vehicle_825dac_idx'),
        ),
    ]
