# Generated by Django 5.0.14 on 2026-02-15 16:46

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_remove_vehicle_operations__vehicle_b29bd0_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='adr_expiry',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='depreciation_years',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='insurance_expiry',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='kteo_expiry',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='pallets_capacity',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='residual_value',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='acquisition_date',
            field=models.DateField(blank=True, help_text='Ημερομηνία που η εταιρεία αγόρασε το όχημα', null=True, verbose_name='Ημερομηνία Απόκτησης από Εταιρεία'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='cargo_height_m',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Εσωτερικό ύψος χώρου φορτίου', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Ύψος Χώρου Φορτίου (m)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='cargo_length_m',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Εσωτερικό μήκος χώρου φορτίου', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Μήκος Χώρου Φορτίου (m)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='cargo_width_m',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Εσωτερικό πλάτος χώρου φορτίου', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Πλάτος Χώρου Φορτίου (m)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='engine_capacity_cc',
            field=models.IntegerField(blank=True, help_text='Κωδικός P.1 - Κυβισμός σε cm³', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Κυβισμός Κινητήρα (P.1)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='first_registration_date',
            field=models.DateField(blank=True, help_text='Κωδικός B - Ημερομηνία πρώτης άδειας κυκλοφορίας', null=True, verbose_name='Ημερομηνία Πρώτης Άδειας (B)'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='color',
            field=models.CharField(blank=True, help_text='Κωδικός R από την άδεια', max_length=30, verbose_name='Χρώμα (R)'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='emission_class',
            field=models.CharField(blank=True, choices=[('EURO_3', 'Euro 3'), ('EURO_4', 'Euro 4'), ('EURO_5', 'Euro 5'), ('EURO_6', 'Euro 6'), ('EURO_6C', 'Euro 6c'), ('EURO_6D', 'Euro 6d'), ('ELECTRIC_ZERO', 'Μηδενικές Εκπομπές (Electric/Zero)')], help_text='Κρίσιμο για διεθνή διόδια και περιβαλλοντικές ζώνες', max_length=20, null=True, verbose_name='Κατηγορία Εκπομπών'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(choices=[('DIESEL', 'Πετρέλαιο (Diesel)'), ('PETROL', 'Βενζίνη (Petrol/Gasoline)'), ('ELECTRIC', 'Ηλεκτρικό (Electric)'), ('GAS', 'Φυσικό Αέριο (CNG/LNG)'), ('HYBRID', 'Υβριδικό (Hybrid)')], default='DIESEL', help_text='Κωδικός P.3 από την άδεια', max_length=20, verbose_name='Τύπος Καυσίμου (P.3)'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='gross_weight_kg',
            field=models.IntegerField(blank=True, help_text='Κωδικός F.1 - Μέγιστο επιτρεπόμενο βάρος', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Μικτό Βάρος (F.1)'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='height_m',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Κρίσιμο για γέφυρες και σήραγγες', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Ύψος'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='horsepower',
            field=models.IntegerField(blank=True, help_text='Κωδικός P.2 - Ισχύς κινητήρα σε HP', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Ιπποδύναμη (P.2)'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='length_total_m',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Κωδικός L - Συμπεριλαμβανομένων προεξοχών', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Συνολικό Μήκος (L)'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='license_plate',
            field=models.CharField(help_text='Κωδικός A από την άδεια κυκλοφορίας', max_length=20, unique=True, verbose_name='Αριθμός Κυκλοφορίας (A)'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='make',
            field=models.CharField(help_text='Κωδικός D.1 από την άδεια', max_length=50, verbose_name='Μάρκα (D.1)'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.CharField(help_text='Κωδικός D.2 από την άδεια', max_length=50, verbose_name='Τύπος/Μοντέλο (D.2)'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='purchase_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Αξία κατά την απόκτηση από την εταιρεία', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Αξία Αγοράς (€)'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='seats',
            field=models.IntegerField(blank=True, help_text='Κωδικός S.1 - Για λεωφορεία και επιβατικά', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Θέσεις Επιβατών (S.1)'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Ενεργό'), ('INACTIVE', 'Ανενεργό'), ('SOLD', 'Πωλήθηκε')], default='ACTIVE', max_length=20, verbose_name='Κατάσταση'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='unladen_weight_kg',
            field=models.IntegerField(blank=True, help_text='Κωδικός G - Βάρος κενού οχήματος', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Απόβαρο (G)'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vin',
            field=models.CharField(blank=True, help_text='Κωδικός E - 17-ψήφιος αριθμός πλαισίου', max_length=17, null=True, unique=True, verbose_name='Αριθμός Πλαισίου (E)'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='width_m',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Εξωτερικό πλάτος οχήματος', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Πλάτος'),
        ),
    ]
