# Generated by Django 5.0.2 on 2026-02-15 18:36

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_remove_vehicle_adr_expiry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='average_fuel_consumption',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Υπολογίζεται από ιστορικό ή εισάγεται χειροκίνητα', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Μέση Κατανάλωση Καυσίμου (L/100km)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='average_tire_cost_per_km',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Π.χ. 0.05 για 5 λεπτά ανά χιλιόμετρο', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='Μέσο Κόστος Ελαστικών ανά km (€/km)'),
        ),
    ]
