# Generated by Django 5.0.14 on 2026-02-27 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_employee_vehicle_add_personnel_driver_fields'),
        ('operations', '0006_vehicle_average_fuel_consumption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelentry',
            name='driver',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'position__is_driver_role': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuel_entries_as_driver', to='core.employee', verbose_name='Οδηγός'),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='driver',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'position__is_driver_role': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_reports_as_driver', to='core.employee', verbose_name='Οδηγός'),
        ),
    ]
