"""
Django settings for greekfleet project.

Generated by 'django-admin startproject' using Django 5.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
# Define DEBUG first to use in SECRET_KEY logic
DEBUG = os.getenv('DEBUG', 'True').lower() in ['true', '1', 't']

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

if not SECRET_KEY:
    if not DEBUG:
        raise ImproperlyConfigured(
            'The SECRET_KEY environment variable must be set in production. '
            'Generate a secure key using: python -c "from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())"'
        )
    else:
        # Development fallback - NEVER use in production
        SECRET_KEY = 'django-insecure-dev-only-static-key-for-local-development'
        print('WARNING: Using a default SECRET_KEY for development. Set SECRET_KEY in .env for production.')

# Robust ALLOWED_HOSTS parsing (strips whitespace, filters empty strings)
ALLOWED_HOSTS = [h.strip() for h in os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',') if h.strip()]


# Application definition

INSTALLED_APPS = [
    # Django Unfold (must be before django.contrib.admin)
    'unfold',
    'unfold.contrib.filters',
    'unfold.contrib.forms',
    
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party apps
    'polymorphic',
    'django_extensions',
    # Local apps
    'core',
    'operations',
    'finance',
    'web',
    'accounts',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'greekfleet.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'greekfleet.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': os.getenv('DB_ENGINE', 'django.db.backends.sqlite3'),
        'NAME': os.getenv('DB_NAME', str(BASE_DIR / 'db.sqlite3')),
        'USER': os.getenv('DB_USER', ''),
        'PASSWORD': os.getenv('DB_PASSWORD', ''),
        'HOST': os.getenv('DB_HOST', ''),
        'PORT': os.getenv('DB_PORT', ''),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'el'

TIME_ZONE = 'Europe/Athens'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Date/Time Input Formats (Greek format: DD/MM/YYYY)
DATE_INPUT_FORMATS = [
    '%d/%m/%Y',  # 25/12/2026
    '%d-%m-%Y',  # 25-12-2026
    '%Y-%m-%d',  # 2026-12-25 (ISO format)
]

DATETIME_INPUT_FORMATS = [
    '%d/%m/%Y %H:%M',  # 25/12/2026 14:30
    '%d/%m/%Y %H:%M:%S',  # 25/12/2026 14:30:00
    '%Y-%m-%d %H:%M:%S',  # ISO format
]

# Number formatting (Greek style: 1.234,56)
USE_THOUSAND_SEPARATOR = True
THOUSAND_SEPARATOR = '.'
DECIMAL_SEPARATOR = ','


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Authentication
LOGIN_URL = 'accounts:login'
LOGIN_REDIRECT_URL = 'web:dashboard'
LOGOUT_REDIRECT_URL = 'accounts:login'

# Django Unfold Configuration
UNFOLD = {
    "SITE_TITLE": "GreekFleet 360 Admin",
    "SITE_HEADER": "GreekFleet 360",
    "SITE_URL": "/",
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
        "navigation": [
            {
                "title": "SaaS Platform",
                "separator": True,
                "items": [
                    {
                        "title": "Companies",
                        "icon": "business",
                        "link": lambda request: "/admin/core/company/",
                    },
                    {
                        "title": "Users",
                        "icon": "people",
                        "link": lambda request: "/admin/auth/user/",
                    },
                    {
                        "title": "User Profiles",
                        "icon": "badge",
                        "link": lambda request: "/admin/accounts/userprofile/",
                    },
                ],
            },
            {
                "title": "Master Data / Templates",
                "separator": True,
                "items": [
                    {
                        "title": "Expense Families",
                        "icon": "folder_open",
                        "link": lambda request: "/admin/finance/expensefamily/",
                    },
                    {
                        "title": "Expense Categories",
                        "icon": "category",
                        "link": lambda request: "/admin/finance/expensecategory/",
                    },
                    {
                        "title": "Θέσεις Εργασίας",
                        "icon": "work",
                        "link": lambda request: "/admin/core/employeeposition/",
                    },
                ],
            },
            {
                "title": "Tenant Data (View Only)",
                "separator": True,
                "items": [
                    {
                        "title": "Cost Centers",
                        "icon": "account_balance",
                        "link": lambda request: "/admin/finance/costcenter/",
                    },
                    {
                        "title": "Company Expenses",
                        "icon": "receipt_long",
                        "link": lambda request: "/admin/finance/companyexpense/",
                    },
                    {
                        "title": "Transport Orders",
                        "icon": "local_shipping",
                        "link": lambda request: "/admin/finance/transportorder/",
                    },
                    {
                        "title": "Fleet Management",
                        "icon": "directions_car",
                        "link": lambda request: "/fleet/",
                    },
                    {
                        "title": "Drivers",
                        "icon": "person",
                        "link": lambda request: "/admin/core/driverprofile/",
                    },
                    {
                        "title": "Υπάλληλοι",
                        "icon": "badge",
                        "link": lambda request: "/admin/core/employee/",
                    },
                    {
                        "title": "Fuel Entries",
                        "icon": "local_gas_station",
                        "link": lambda request: "/admin/operations/fuelentry/",
                    },
                    {
                        "title": "Service Logs",
                        "icon": "build",
                        "link": lambda request: "/admin/operations/servicelog/",
                    },
                ],
            },
        ],
    },
}

# Email Configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.example.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
# Robust boolean parsing for email security settings
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True').lower() in ['true', '1', 't']
EMAIL_USE_SSL = os.getenv('EMAIL_USE_SSL', 'False').lower() in ['true', '1', 't']
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER or 'noreply@example.com')
SERVER_EMAIL = os.getenv('SERVER_EMAIL', EMAIL_HOST_USER or 'server@example.com')

# Admin Notifications
ADMINS = [('Administrator', os.getenv('ADMIN_EMAIL', 'admin@example.com'))]
MANAGERS = ADMINS

# ============================================================================
# PRODUCTION SECURITY SETTINGS
# ============================================================================
# Uncomment these settings when deploying to production (DEBUG=False)

# SECURE_SSL_REDIRECT = True  # Redirect all HTTP to HTTPS
# SESSION_COOKIE_SECURE = True  # Send session cookie only over HTTPS
# CSRF_COOKIE_SECURE = True  # Send CSRF cookie only over HTTPS
# SECURE_HSTS_SECONDS = 31536000  # 1 year - Enable HTTP Strict Transport Security
# SECURE_HSTS_INCLUDE_SUBDOMAINS = True  # Apply HSTS to all subdomains
# SECURE_HSTS_PRELOAD = True  # Allow browser HSTS preload
# SECURE_CONTENT_TYPE_NOSNIFF = True  # Prevent MIME-sniffing
# SECURE_BROWSER_XSS_FILTER = True  # Enable browser XSS filter
# X_FRAME_OPTIONS = 'DENY'  # Prevent clickjacking

# Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
    },
    'handlers': {
        'file': {
            'level': 'ERROR',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'system_errors.log',
            'maxBytes': 1024 * 1024 * 10,  # 10 MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'mail_admins': {
            'level': 'ERROR',
            'class': 'django.utils.log.AdminEmailHandler',
            'filters': ['require_debug_false'],
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file', 'mail_admins'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['file', 'mail_admins'],
            'level': 'ERROR',
            'propagate': False,
        },
    },
}
